### ISSUE TITLE
Deliver offline installer

### ISSUE THREAD

**Issue by PW999** [DavidRogers/kato#7]
The installer doesn't work when used behind a proxy with authentication.

> An error occurred trying to download 'http://fieryjoy.com/apps/kato/Kato.application'.
>
> See the setup log file located at 'C:\Users\pwuyts2\AppData\Local\Temp\VSDC210.tmp\install.log' for > more information.

Downloading the .application doesn't fix it either:
> System.Net.WebException
> 		- The remote server returned an error: (407) Proxy Authentication Required.
> 		- Source: System
> 		- Stack trace:
> 			at System.Net.HttpWebRequest.GetResponse()
> 			at System.Deployment.Application.SystemNetDownloader.DownloadSingleFile(DownloadQueueItem next)

**Comment by DavidRogers** [comment]
Thanks, Ill take a look to see if there is a quick fix for this.

**Comment by sharwell** [comment]
If you set up an AppVeyor build for this, you could have the build artifacts (binaries) attached to the builds. Users looking for a download would have the option of using the artifacts from the latest build if they didn't want to use the ClickOnce installer.
